---
title: "Forecast Challenge - Beetles Theme - Random Walk Model"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
```

```{r}
# Data download 
#read in the targets data
targets <- read_csv("https://data.ecoforecast.org/neon4cast-targets/beetles/beetles-targets.csv.gz")
# To work with only a single site
targets <- targets[targets$site_id == "DSNY", ]
# Filter to just abundance
targets <- targets[targets$variable == "abundance",]

```
# Random walk


```{r}
RandomWalk = "
model{
  
  #### Data Model
  for(t in 1:n){
    y[t] ~ dnorm(x[t],tau_obs)
  }
  
  #### Process Model
  for(t in 2:n){
    x[t]~dnorm(x[t-1],tau_add)
  }
  
  #### Priors
  x[1] ~ dnorm(x_ic,tau_ic)
  tau_obs ~ dgamma(a_obs,r_obs)
  tau_add ~ dgamma(a_add,r_add)
  
  #### In sample prediction 
  for(t in 2:n){
    ypred[t] ~ dnorm(y[t-1],tau_obs)
  }
  
}
"

## Define data and priors as list
y = log(targets$observation + 0.001)
data <- list(y=y,n=length(y),      ## data, adding 0.001 because you can't take the log of 0 value 
             x_ic=log(1000),tau_ic=100, ## initial condition prior
             a_obs=1,r_obs=1,           ## obs error prior
             a_add=1,r_add=1            ## process error prior
             )

## Define the initial state of the model's parameters for each chain in the MCMC
nchain = 3
init <- list()
for(i in 1:nchain){
  y.samp = sample(y,length(y),replace=TRUE)
  init[[i]] <- list(tau_add=1/var(diff(log(y.samp))),  ## initial guess on process precision
                    tau_obs=5/var(log(y.samp)))        ## initial guess on obs precision
}

j.model   <- jags.model (file = textConnection(RandomWalk),
                             data = data,
                             inits = init,
                             n.chains = 3)
```

```{r, fig.asp = 1.0}
## burn-in
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("tau_add","tau_obs", "ypred"),
                                n.iter = 1000)
plot(jags.out)
```


# Posterior analysis 

```{r}
samples <- as.matrix(jags.out)

time <- targets$datetime
time.rng = c(1,length(targets$datetime))       ## adjust to zoom in and out
y.pred <- grep("^y",colnames(samples)) ## grab all columns that start with the letter y (grabs all predictions)
ci <- apply(samples[,y.pred],2,quantile,c(0.025,0.5,0.975)) ## calculate 95% confidence intervals

##### Plotting 

# par(mfrow=c(1, 3))
# Observed data plot
plot(time[-1], ci[2,],type='n',ylim=range(y,na.rm=TRUE),ylab="Log(abundance)", xlab="Time", main = "Observed")
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
points(time[-1],y[-1],pch="+",cex=0.5)
lines(time[-1], y[-1])

# Observed and Estimated data plot
plot(time[-1], ci[2,],type='n',ylim=range(y,na.rm=TRUE),ylab="Log(abundance)", xlab = "Time", main = "Estimated")
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time[-1],ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time[-1],y[-1],pch="+",cex=0.5)
lines(time[-1], y[-1])
points(time[-1], colMeans(samples[, y.pred]), pch = "x", col = "blue")

```

# Forecast 

```{r}
# Hindcast 2022 using same JAGS model but with missing data for 2022

# remove 2022
rmdate <- grep("2022",targets$datetime )
ymiss <- log(targets$observation + 0.001)
ymiss[rmdate] <- NA
ymiss # NAs for all of 2022


# re
data <- list(y=ymiss,n=length(y),           ## data
             x_ic=log(1000),tau_ic=100, ## initial condition prior
             a_obs=1,r_obs=1,           ## obs error prior
             a_add=1,r_add=1            ## process error prior
             )

# JAGS model 
j.model   <- jags.model (file = textConnection(RandomWalk),
                         data = data,
                         inits = init,
                         n.chains = 3)

## burn-in
jags.out.pred   <- coda.samples (model = j.model,
                            variable.names = c("tau_obs", "ypred"),
                            n.iter = 10000)
# plot(jags.out)


# Visualize 

samples <- as.matrix(jags.out.pred)
y.pred <- grep("^y",colnames(samples)) ## grab all columns that start with the letter y
ci <- apply(samples[,y.pred],2,quantile,c(0.025,0.5,0.975)) ## model was fit on log scale

plot(time[-1], ci[2,],type='n',ylim=range(y,na.rm=TRUE),ylab="Log(abundance)", main = "Forecast")
# ## adjust x-axis label to be monthly if zoomed
# if(diff(time.rng) < 100){
#   axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
# }
ecoforecastR::ciEnvelope(time[-1],ci[1,],ci[3,],col=ecoforecastR::col.alpha("orange",0.75))
points(time[-1],ymiss[-1],pch="+",cex=0.5)
lines(time[-1], ymiss[-1])
points(time[-1], colMeans(samples[,y.pred]), pch = "x", col = "brown")

```

# Comparison of observation error by site 
```{r}
# Insert site name
hist(samples[, 1], main = paste0("DSNY (n=", length(y), ")"))
abline(v = mean(samples[, 1]), col = 'red')
```
